hansck/LatihanVersionControl

src/main/java/com/mycompany/latihanversioncontrol/students/Axell.java

create new axell class

---

src/main/java/com/mycompany/latihanversioncontrol/students/Hans.java

add sout in Hans.java

---

src/main/java/com/mycompany/latihanversioncontrol/students/Matthew.java

ini Matthew

---

src/main/java/com/mycompany/latihanversioncontrol/students/Adithia.java

Add Feature Adit

---

src/main/java/com/mycompany/latihanversioncontrol/students/Jason.java

add feature jason

---

src/main/java/Renald.java
src/main/java/Renald/java.java
src/main/java/com/mycompany/latihanversioncontrol/students/renald.java

Feature renald

---

src/main/java/HansJK.java
src/main/java/com/mycompany/latihanversioncontrol/students/HansJK.java

Feature Hans JK

---

src/main/java/com/mycompany/latihanversioncontrol/students/Dewi.java

Create Feature Dewi

---

src/main/java/com/mycompany/latihanversioncontrol/students/Edwan.java

perubahanEdwan

---

src/main/java/com/mycompany/latihanversioncontrol/students/nicholas.java

add Nicholas

---

src/main/java/com/mycompany/latihanversioncontrol/students/alvin.java

Natanael alvin

---

src/main/java/com/mycompany/latihanversioncontrol/students/SebastianBerto.java

1118054 - Sebastian Berto

---

src/main/java/com/mycompany/latihanversioncontrol/students/Vito.java

Izin bergabung Ko , Trimakasih

Vito Vandersen

---

src/main/java/com/mycompany/latihanversioncontrol/students/Timotius.java

Latihan Git

---

src/main/java/com/mycompany/latihanversioncontrol/students/Alvin27.java

pull request

---

.idea/.gitignore
.idea/compiler.xml
.idea/encodings.xml
.idea/jarRepositories.xml
.idea/misc.xml
.idea/vcs.xml
src/main/java/com/mycompany/latihanversioncontrol/students/DavidKharisElioM_2022.java

David kharis elio m 2022

---

src/main/java/class2022/jovi.java

commit jovi

---

src/main/java/class2022/FriendlySB.java

Test Branch

---

src/main/java/class2022/JonathanHA2022.java

Test pull merger request by Jonathan HA

Test pull merger request 

---

src/main/java/class2022/Michael.java

update method hei di package class 2022

initialize commit

---

src/main/java/class2022/JimmyFXW.java

feature hello

---

src/main/java/class2022/KevinNathaniel.java

init commit

---

src/main/java/com/mycompany/latihanversioncontrol/students/NathanaelT.java

print hello world

---

src/main/java/class2022/NicoJonathanSetiawan.java

Nambahin package class2022 (yang sebelumnya kelupaan)

Nambahin package class2022 (yang sebelumnya kelupaan)

---

src/main/java/class2023/Vincent.java

Create Feature vincent

---

src/main/java/class2023/darrenstn.java

Create main with print name

---

src/main/java/class2024/JerrycoAxel2024.java

Nambah File Jerryco

---

src/main/java/class2024/Aloy.java

Create File Aloy

---

src/main/java/class2024/BostonManalu2024.java

Boston bikin branch cuy

---

src/main/java/class2024/calvin2024.java

Calvin estanto zendrato

---

src/main/java/class2024/FelixGalvin.java

Felix bkin branch
